# Load libraries

In [1]:
import pandas as pd
import numpy as np

# Load Dataset

In [6]:
# reading ratings file:
r_cols=['user_id', 'movie_id', 'rating', 'unix_timestamp']

ratings=pd.read_csv('ml-100k/u.data' , sep='\t' , names=r_cols, encoding='latin-1')

In [7]:
ratings

       user_id  movie_id  rating  unix_timestamp
0          196       242       3       881250949
1          186       302       3       891717742
2           22       377       1       878887116
3          244        51       2       880606923
4          166       346       1       886397596
...        ...       ...     ...             ...
99995      880       476       3       880175444
99996      716       204       5       879795543
99997      276      1090       1       874795795
99998       13       225       2       882399156
99999       12       203       3       879959583

[100000 rows x 4 columns]

In [8]:
# Finding unique entries
n_users=ratings.user_id.unique().shape[0]
n_items=ratings['movie_id'].unique().shape[0]

In [9]:
print("Number of user ",n_users)
print("Number of items ",n_items)

Number of user  943
Number of items  1682

# Create pivot table for user and movie based on ratings

In [11]:
datama=ratings.pivot_table(index='user_id',columns='movie_id',values='rating')
datama

movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
940,NaN,NaN,NaN,2.0,NaN,NaN,4.0,5.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
941,5.0,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
943,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
datamatrix=datama.replace(np.nan,0)
datamatrix

movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,2.0,0.0,0.0,4.0,5.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
943,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Find Cosine Similarity for user and Item

In [14]:
from sklearn.metrics.pairwise import pairwise_distances
user_similarity=pairwise_distances(datamatrix,metric='cosine')
item_similarity=pairwise_distances(datamatrix.T,metric='cosine')

# Using formula for user and item we are calcuating the score value

In [18]:
def predict(ratings, similarity, type='user'):
    if type == 'user':
        mean_user_rating = ratings.mean(axis=1)
        # Convert mean_user_rating to numpy array
        mean_user_rating = np.array(mean_user_rating)
        #We use np.newaxis so that mean_user_rating has same format as ratings
        ratings_diff = (ratings - mean_user_rating[:, np.newaxis])
        pred = mean_user_rating[:, np.newaxis] + similarity.dot(ratings_diff) / np.array([np.abs(similarity).sum(axis=1)]).T
    elif type == 'item':
        pred = ratings.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])
    return pred

In [19]:
# prediction Table
user_prediction = predict(datamatrix, user_similarity, type='user')
item_prediction = predict(datamatrix, item_similarity, type='item')

# As per User based filtering ,first have to find similarity between the input user and others

In [20]:
#1. Select input user

input_item=78

In [22]:
#2. Convert the user_sim table into DataFrame

item_sim_table=pd.DataFrame(item_similarity)

In [26]:
similar_input_item=item_sim_table[input_item].sort_values(ascending=True).head(5).index
similar_input_item

Index([78, 173, 95, 55, 209], dtype='int64')

In [27]:
#4.Convert in to list
similar_item_input=list(similar_input_item)

In [29]:
#5. Using similar_item_input,can select movie id from ratings table

similar_item_userid_list=[]
for sim_item in similar_item_input:
    sim=list(ratings[ratings['movie_id']==sim_item]['user_id'])
    similar_item_userid_list.append(sim)

In [30]:
similar_item_userid_list

[[83,
  276,
  7,
  1,
  62,
  405,
  148,
  254,
  314,
  92,
  56,
  95,
  303,
  472,
  38,
  393,
  778,
  417,
  749,
  222,
  642,
  194,
  545,
  901,
  399,
  13,
  450,
  796,
  620,
  416,
  566,
  712,
  378],
 [213,
  222,
  58,
  275,
  28,
  307,
  125,
  22,
  295,
  49,
  5,
  95,
  320,
  102,
  188,
  189,
  232,
  64,
  345,
  270,
  62,
  57,
  128,
  327,
  253,
  200,
  374,
  96,
  279,
  65,
  297,
  347,
  292,
  352,
  92,
  301,
  243,
  401,
  13,
  278,
  130,
  399,
  221,
  180,
  299,
  312,
  202,
  334,
  437,
  43,
  419,
  433,
  412,
  435,
  73,
  98,
  361,
  59,
  109,
  409,
  144,
  110,
  158,
  135,
  198,
  407,
  218,
  354,
  42,
  346,
  452,
  455,
  454,
  316,
  315,
  503,
  60,
  244,
  340,
  469,
  389,
  117,
  246,
  406,
  56,
  474,
  393,
  373,
  24,
  521,
  177,
  522,
  1,
  508,
  603,
  392,
  575,
  417,
  311,
  94,
  51,
  457,
  497,
  640,
  269,
  468,
  479,
  496,
  271,
  618,
  326,
  666,
  70,
  99,
  268,
  535,
  579,
  288,
  350,
  145,
  363,
  538,
  592,
  554,
  124,
  249,
  506,
  152,
  385,
  484,
  643,
  6,
  234,
  214,
  648,
  405,
  654,
  514,
  628,
  768,
  747,
  377,
  593,
  472,
  625,
  586,
  85,
  528,
  391,
  276,
  661,
  379,
  748,
  815,
  545,
  476,
  659,
  749,
  838,
  567,
  339,
  676,
  682,
  194,
  14,
  201,
  398,
  588,
  196,
  711,
  495,
  721,
  378,
  481,
  450,
  757,
  850,
  77,
  795,
  25,
  577,
  764,
  798,
  882,
  868,
  488,
  864,
  790,
  796,
  493,
  606,
  291,
  886,
  737,
  524,
  908,
  875,
  763,
  561,
  712,
  892,
  709,
  762,
  420,
  889,
  885,
  686,
  629,
  293,
  807,
  645,
  280,
  698,
  321,
  684,
  880,
  621,
  647,
  921,
  187,
  799,
  766,
  566,
  871,
  756,
  562,
  466,
  804,
  314,
  601,
  663,
  922,
  642,
  499,
  924,
  823,
  704,
  97,
  862,
  741,
  933,
  734,
  639,
  394,
  847,
  738,
  758,
  664,
  913,
  332,
  700,
  622,
  912,
  844,
  840,
  751,
  660,
  715,
  210,
  505,
  11,
  632,
  940,
  786,
  259,
  854,
  429,
  41,
  283,
  916,
  897,
  934,
  416,
  830,
  932,
  44,
  620,
  896,
  303,
  387,
  483,
  846,
  707,
  286,
  899,
  928,
  877,
  421,
  370,
  907,
  753,
  883,
  537,
  151,
  89,
  148,
  710,
  771,
  911,
  556,
  178,
  705,
  679,
  541,
  650,
  716,
  7,
  943,
  890,
  487,
  542,
  223,
  23,
  831,
  727,
  264,
  305,
  336,
  843,
  848,
  344,
  805,
  904,
  207],
 [38,
  308,
  44,
  314,
  28,
  52,
  6,
  83,
  244,
  301,
  216,
  234,
  56,
  325,
  280,
  342,
  263,
  275,
  253,
  299,
  59,
  43,
  20,
  49,
  198,
  271,
  64,
  283,
  297,
  332,
  42,
  330,
  85,
  194,
  186,
  320,
  23,
  471,
  397,
  223,
  389,
  303,
  334,
  398,
  16,
  380,
  450,
  178,
  246,
  532,
  230,
  524,
  13,
  60,
  393,
  487,
  399,
  201,
  543,
  70,
  5,
  466,
  84,
  313,
  295,
  435,
  433,
  577,
  222,
  537,
  437,
  18,
  381,
  456,
  374,
  493,
  566,
  606,
  286,
  262,
  233,
  429,
  497,
  650,
  250,
  268,
  373,
  363,
  436,
  95,
  109,
  661,
  102,
  711,
  698,
  378,
  417,
  92,
  741,
  561,
  344,
  200,
  551,
  738,
  468,
  495,
  716,
  455,
  758,
  731,
  610,
  327,
  727,
  521,
  804,
  766,
  830,
  523,
  130,
  751,
  479,
  848,
  805,
  514,
  705,
  806,
  823,
  885,
  506,
  892,
  843,
  407,
  621,
  632,
  710,
  654,
  896,
  347,
  660,
  279,
  899,
  940,
  542,
  402,
  764,
  889,
  290,
  847,
  798,
  554,
  682,
  815,
  1,
  340,
  592,
  942,
  276,
  749,
  648,
  897,
  622,
  715,
  291,
  747,
  776,
  454,
  625,
  870,
  756,
  882,
  864,
  927,
  664,
  881,
  125,
  933,
  846,
  588,
  734,
  406,
  821,
  699,
  620,
  387,
  505,
  618,
  902,
  795,
  536,
  541,
  472,
  807,
  886,
  865,
  771,
  868,
  901,
  712,
  545,
  796,
  913,
  887,
  642,
  679,
  850,
  484,
  826,
  880,
  844,
  405,
  757,
  184,
  851,
  416,
  919,
  779,
  822,
  922,
  786],
 [308,
  16,
  216,
  197,
  37,
  137,
  267,
  44,
  251,
  339,
  130,
  343,
  352,
  315,
  248,
  87,
  328,
  293,
  363,
  286,
  303,
  371,
  249,
  269,
  178,
  49,
  142,
  347,
  94,
  246,
  268,
  393,
  195,
  387,
  62,
  327,
  110,
  24,
  296,
  416,
  479,
  177,
  59,
  183,
  425,
  262,
  429,
  118,
  207,
  291,
  109,
  297,
  198,
  218,
  158,
  545,
  405,
  445,
  506,
  23,
  144,
  346,
  524,
  645,
  135,
  650,
  619,
  653,
  551,
  92,
  299,
  559,
  487,
  454,
  417,
  627,
  577,
  756,
  583,
  361,
  466,
  399,
  221,
  442,
  145,
  447,
  846,
  826,
  213,
  655,
  102,
  606,
  250,
  629,
  823,
  632,
  908,
  682,
  805,
  1,
  932,
  854,
  385,
  592,
  548,
  788,
  276,
  378,
  877,
  889,
  186,
  640,
  374,
  883,
  739,
  896,
  897,
  763,
  727,
  880,
  162,
  499,
  8,
  160,
  495,
  201,
  943,
  751,
  621,
  875,
  833,
  844,
  864,
  474,
  916,
  643,
  804,
  497,
  453,
  870,
  435,
  468,
  868,
  618,
  671,
  658,
  561,
  886,
  214],
 [28,
  218,
  16,
  201,
  177,
  303,
  178,
  305,
  234,
  18,
  6,
  87,
  269,
  230,
  98,
  44,
  160,
  1,
  144,
  62,
  312,
  385,
  268,
  119,
  279,
  293,
  276,
  188,
  128,
  23,
  370,
  244,
  297,
  411,
  85,
  283,
  226,
  406,
  59,
  41,
  5,
  92,
  151,
  232,
  64,
  145,
  342,
  308,
  124,
  468,
  222,
  387,
  339,
  158,
  458,
  445,
  286,
  148,
  292,
  327,
  311,
  508,
  506,
  58,
  77,
  476,
  48,
  94,
  535,
  299,
  583,
  429,
  189,
  373,
  307,
  479,
  474,
  542,
  416,
  315,
  625,
  554,
  95,
  457,
  267,
  493,
  392,
  194,
  537,
  527,
  409,
  567,
  704,
  480,
  425,
  666,
  407,
  579,
  524,
  645,
  125,
  187,
  664,
  447,
  643,
  785,
  442,
  249,
  615,
  823,
  60,
  778,
  661,
  804,
  766,
  49,
  738,
  650,
  354,
  848,
  138,
  763,
  561,
  655,
  622,
  109,
  899,
  239,
  868,
  870,
  929,
  641,
  795,
  790,
  606,
  686,
  514,
  334,
  843,
  747,
  556,
  932,
  833,
  805,
  90,
  551,
  933,
  405,
  709,
  883,
  295,
  864,
  773,
  896,
  456,
  13,
  846,
  749,
  536,
  716,
  741,
  748,
  881,
  214,
  391,
  330,
  640,
  22,
  840,
  660,
  885,
  934,
  758,
  911,
  880,
  940,
  796,
  389,
  916,
  417,
  727,
  682,
  721,
  886,
  908,
  751,
  296,
  264,
  889,
  806,
  913]]

In [31]:
#6. Convert all the list as single
import itertools
similar_item_userid_single_list=list(itertools.chain.from_iterable(similar_item_userid_list))

In [32]:
#7. Unique movieid from the list

unique_userid_similar_item=set(similar_item_userid_single_list)

In [33]:
len(unique_userid_similar_item)

428

In [34]:
#8. Input user watched movie_list

input_item_watched_userid=list(ratings[ratings['movie_id']==input_item]['user_id'].values)

In [43]:
input_item_watched_userid

[83,
 276,
 7,
 1,
 62,
 405,
 148,
 254,
 314,
 92,
 56,
 95,
 303,
 472,
 38,
 393,
 778,
 417,
 749,
 222,
 642,
 194,
 545,
 901,
 399,
 13,
 450,
 796,
 620,
 416,
 566,
 712,
 378]

In [36]:
#9. Create a list which should have recom movieid to the input user

recom=[]
for per_id in unique_userid_similar_item:
    if(per_id in input_item_watched_userid):
        pass
    else:
        recom.append(per_id)

In [37]:
len(recom)

395

In [38]:
sorted(recom)

[5,
 6,
 8,
 11,
 14,
 16,
 18,
 20,
 22,
 23,
 24,
 25,
 28,
 37,
 41,
 42,
 43,
 44,
 48,
 49,
 51,
 52,
 57,
 58,
 59,
 60,
 64,
 65,
 70,
 73,
 77,
 84,
 85,
 87,
 89,
 90,
 94,
 96,
 97,
 98,
 99,
 102,
 109,
 110,
 117,
 118,
 119,
 124,
 125,
 128,
 130,
 135,
 137,
 138,
 142,
 144,
 145,
 151,
 152,
 158,
 160,
 162,
 177,
 178,
 180,
 183,
 184,
 186,
 187,
 188,
 189,
 195,
 196,
 197,
 198,
 200,
 201,
 202,
 207,
 210,
 213,
 214,
 216,
 218,
 221,
 223,
 226,
 230,
 232,
 233,
 234,
 239,
 243,
 244,
 246,
 248,
 249,
 250,
 251,
 253,
 259,
 262,
 263,
 264,
 267,
 268,
 269,
 270,
 271,
 275,
 278,
 279,
 280,
 283,
 286,
 288,
 290,
 291,
 292,
 293,
 295,
 296,
 297,
 299,
 301,
 305,
 307,
 308,
 311,
 312,
 313,
 315,
 316,
 320,
 321,
 325,
 326,
 327,
 328,
 330,
 332,
 334,
 336,
 339,
 340,
 342,
 343,
 344,
 345,
 346,
 347,
 350,
 352,
 354,
 361,
 363,
 370,
 371,
 373,
 374,
 377,
 379,
 380,
 381,
 385,
 387,
 389,
 391,
 392,
 394,
 397,
 398,
 401,
 402,
 406,
 407,
 409,
 411,
 412,
 419,
 420,
 421,
 425,
 429,
 433,
 435,
 436,
 437,
 442,
 445,
 447,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 466,
 468,
 469,
 471,
 474,
 476,
 479,
 480,
 481,
 483,
 484,
 487,
 488,
 493,
 495,
 496,
 497,
 499,
 503,
 505,
 506,
 508,
 514,
 521,
 522,
 523,
 524,
 527,
 528,
 532,
 535,
 536,
 537,
 538,
 541,
 542,
 543,
 548,
 551,
 554,
 556,
 559,
 561,
 562,
 567,
 575,
 577,
 579,
 583,
 586,
 588,
 592,
 593,
 601,
 603,
 606,
 610,
 615,
 618,
 619,
 621,
 622,
 625,
 627,
 628,
 629,
 632,
 639,
 640,
 641,
 643,
 645,
 647,
 648,
 650,
 653,
 654,
 655,
 658,
 659,
 660,
 661,
 663,
 664,
 666,
 671,
 676,
 679,
 682,
 684,
 686,
 698,
 699,
 700,
 704,
 705,
 707,
 709,
 710,
 711,
 715,
 716,
 721,
 727,
 731,
 734,
 737,
 738,
 739,
 741,
 747,
 748,
 751,
 753,
 756,
 757,
 758,
 762,
 763,
 764,
 766,
 768,
 771,
 773,
 776,
 779,
 785,
 786,
 788,
 790,
 795,
 798,
 799,
 804,
 805,
 806,
 807,
 815,
 821,
 822,
 823,
 826,
 830,
 831,
 833,
 838,
 840,
 843,
 844,
 846,
 847,
 848,
 850,
 851,
 854,
 862,
 864,
 865,
 868,
 870,
 871,
 875,
 877,
 880,
 881,
 882,
 883,
 885,
 886,
 887,
 889,
 890,
 892,
 896,
 897,
 899,
 902,
 904,
 907,
 908,
 911,
 912,
 913,
 916,
 919,
 921,
 922,
 924,
 927,
 928,
 929,
 932,
 933,
 934,
 940,
 942,
 943]

In [39]:
# Cross Checking 
sorted(unique_userid_similar_item)

[1,
 5,
 6,
 7,
 8,
 11,
 13,
 14,
 16,
 18,
 20,
 22,
 23,
 24,
 25,
 28,
 37,
 38,
 41,
 42,
 43,
 44,
 48,
 49,
 51,
 52,
 56,
 57,
 58,
 59,
 60,
 62,
 64,
 65,
 70,
 73,
 77,
 83,
 84,
 85,
 87,
 89,
 90,
 92,
 94,
 95,
 96,
 97,
 98,
 99,
 102,
 109,
 110,
 117,
 118,
 119,
 124,
 125,
 128,
 130,
 135,
 137,
 138,
 142,
 144,
 145,
 148,
 151,
 152,
 158,
 160,
 162,
 177,
 178,
 180,
 183,
 184,
 186,
 187,
 188,
 189,
 194,
 195,
 196,
 197,
 198,
 200,
 201,
 202,
 207,
 210,
 213,
 214,
 216,
 218,
 221,
 222,
 223,
 226,
 230,
 232,
 233,
 234,
 239,
 243,
 244,
 246,
 248,
 249,
 250,
 251,
 253,
 254,
 259,
 262,
 263,
 264,
 267,
 268,
 269,
 270,
 271,
 275,
 276,
 278,
 279,
 280,
 283,
 286,
 288,
 290,
 291,
 292,
 293,
 295,
 296,
 297,
 299,
 301,
 303,
 305,
 307,
 308,
 311,
 312,
 313,
 314,
 315,
 316,
 320,
 321,
 325,
 326,
 327,
 328,
 330,
 332,
 334,
 336,
 339,
 340,
 342,
 343,
 344,
 345,
 346,
 347,
 350,
 352,
 354,
 361,
 363,
 370,
 371,
 373,
 374,
 377,
 378,
 379,
 380,
 381,
 385,
 387,
 389,
 391,
 392,
 393,
 394,
 397,
 398,
 399,
 401,
 402,
 405,
 406,
 407,
 409,
 411,
 412,
 416,
 417,
 419,
 420,
 421,
 425,
 429,
 433,
 435,
 436,
 437,
 442,
 445,
 447,
 450,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 466,
 468,
 469,
 471,
 472,
 474,
 476,
 479,
 480,
 481,
 483,
 484,
 487,
 488,
 493,
 495,
 496,
 497,
 499,
 503,
 505,
 506,
 508,
 514,
 521,
 522,
 523,
 524,
 527,
 528,
 532,
 535,
 536,
 537,
 538,
 541,
 542,
 543,
 545,
 548,
 551,
 554,
 556,
 559,
 561,
 562,
 566,
 567,
 575,
 577,
 579,
 583,
 586,
 588,
 592,
 593,
 601,
 603,
 606,
 610,
 615,
 618,
 619,
 620,
 621,
 622,
 625,
 627,
 628,
 629,
 632,
 639,
 640,
 641,
 642,
 643,
 645,
 647,
 648,
 650,
 653,
 654,
 655,
 658,
 659,
 660,
 661,
 663,
 664,
 666,
 671,
 676,
 679,
 682,
 684,
 686,
 698,
 699,
 700,
 704,
 705,
 707,
 709,
 710,
 711,
 712,
 715,
 716,
 721,
 727,
 731,
 734,
 737,
 738,
 739,
 741,
 747,
 748,
 749,
 751,
 753,
 756,
 757,
 758,
 762,
 763,
 764,
 766,
 768,
 771,
 773,
 776,
 778,
 779,
 785,
 786,
 788,
 790,
 795,
 796,
 798,
 799,
 804,
 805,
 806,
 807,
 815,
 821,
 822,
 823,
 826,
 830,
 831,
 833,
 838,
 840,
 843,
 844,
 846,
 847,
 848,
 850,
 851,
 854,
 862,
 864,
 865,
 868,
 870,
 871,
 875,
 877,
 880,
 881,
 882,
 883,
 885,
 886,
 887,
 889,
 890,
 892,
 896,
 897,
 899,
 901,
 902,
 904,
 907,
 908,
 911,
 912,
 913,
 916,
 919,
 921,
 922,
 924,
 927,
 928,
 929,
 932,
 933,
 934,
 940,
 942,
 943]

In [40]:
# Cross Checking
sorted(input_item_watched_userid)

[1,
 7,
 13,
 38,
 56,
 62,
 83,
 92,
 95,
 148,
 194,
 222,
 254,
 276,
 303,
 314,
 378,
 393,
 399,
 405,
 416,
 417,
 450,
 472,
 545,
 566,
 620,
 642,
 712,
 749,
 778,
 796,
 901]

In [42]:
# Checking the common movie list
list(set(unique_userid_similar_item)&set(input_item_watched_userid))

[1,
 642,
 901,
 7,
 393,
 778,
 13,
 399,
 276,
 405,
 148,
 796,
 416,
 417,
 545,
 38,
 303,
 566,
 56,
 314,
 62,
 194,
 450,
 712,
 83,
 472,
 92,
 222,
 95,
 620,
 749,
 378,
 254]

In [44]:
item_pred=pd.DataFrame(item_prediction)

In [45]:
item_pred

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
user_id,,,,,,,,,,,,,,,,,,,,,
1,0.446278,0.475473,0.505938,0.443633,0.512667,0.547939,0.446243,0.463059,0.474916,0.515821,...,0.580579,0.576202,0.582478,0.582478,0.575717,0.588155,0.588155,0.588155,0.573107,0.566696
2,0.108544,0.132957,0.125589,0.124932,0.131178,0.129005,0.110883,0.122223,0.109599,0.121525,...,0.135490,0.136546,0.134829,0.134829,0.134108,0.134458,0.134458,0.134458,0.136576,0.137111
3,0.085685,0.091690,0.087643,0.089966,0.089658,0.089985,0.083492,0.089725,0.085188,0.088331,...,0.089770,0.090506,0.086261,0.086261,0.089201,0.084659,0.084659,0.084659,0.089768,0.090845
4,0.053693,0.059604,0.058114,0.058364,0.059356,0.061472,0.053374,0.058615,0.055905,0.060601,...,0.061349,0.061686,0.061195,0.061195,0.060693,0.057937,0.057937,0.057937,0.061673,0.062281
5,0.224739,0.229171,0.263280,0.226387,0.259973,0.296529,0.232710,0.237109,0.258581,0.275076,...,0.297628,0.295990,0.299922,0.299922,0.298188,0.302051,0.302051,0.302051,0.293373,0.294309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.092574,0.113870,0.110211,0.112040,0.112768,0.123140,0.098578,0.110839,0.098858,0.118579,...,0.123829,0.124430,0.120776,0.120776,0.121360,0.125056,0.125056,0.125056,0.123470,0.124327
940,0.164358,0.184894,0.196502,0.164884,0.195860,0.209652,0.162840,0.165606,0.171761,0.194536,...,0.217536,0.215515,0.219136,0.219136,0.216173,0.218583,0.218583,0.218583,0.216582,0.216819
941,0.032300,0.045024,0.042924,0.043223,0.047493,0.051077,0.032761,0.042646,0.039399,0.047421,...,0.052762,0.053042,0.052692,0.052692,0.051514,0.053028,0.053028,0.053028,0.051910,0.052280
942,0.157779,0.174095,0.189000,0.163514,0.186140,0.194151,0.164910,0.156970,0.167038,0.181295,...,0.197537,0.194479,0.198479,0.198479,0.197969,0.199793,0.199793,0.199793,0.197394,0.200031
943,0.247672,0.244892,0.282630,0.241440,0.279338,0.335121,0.250015,0.263325,0.273579,0.313885,...,0.336816,0.338652,0.338585,0.338585,0.336956,0.344104,0.344104,0.344104,0.330514,0.331025

In [46]:
#s[187].values >=0.4

In [47]:
item_pred[input_item]

user_id
1      0.431165
2      0.120833
3      0.087827
4      0.055168
5      0.215771
         ...
939    0.105969
940    0.157803
941    0.039684
942    0.147559
943    0.223707
Name: 78, Length: 943, dtype: float64

In [51]:
item_pred[input_item]

user_id
1      0.431165
2      0.120833
3      0.087827
4      0.055168
5      0.215771
         ...
939    0.105969
940    0.157803
941    0.039684
942    0.147559
943    0.223707
Name: 78, Length: 943, dtype: float64

In [52]:
# From recomd list select hightest rated film which would like by the user. Based on User prediction

highest_Rated=[]
input_item_pre=pd.DataFrame(item_pred[input_item])
input_item_pred=input_item_pre.T
for re in recom:
    value=input_item_pred[re].values
    if(value>=1):
        highest_Rated.append(re)

In [53]:
len(highest_Rated)

1

In [54]:
# Checking the common movie list
list(set(recom)&set(input_item_watched_userid))

[]

In [55]:
def itembased(input_item,item_similarity,item_predictions,similar_item_count,thres):
    #Convert the user_sim table into DataFrame
    item_sim_table=pd.DataFrame(item_similarity)
    #Find similarity user for 78 using cosine table
    similar_input_item= item_sim_table[input_item].sort_values(ascending=True).head(similar_item_count).index
    #Convert in to list
    similar_item_input=list(similar_input_item) 
    #Using similar_user_input,can select movie id from ratings table
    similar_item_userid_list=[]
    for sim_item in similar_item_input:
        sim=list(ratings[ratings['movie_id']==sim_item]['user_id'])
        similar_item_userid_list.append(sim)
    #Converting as a whole list
    import itertools
    similar_item_userid_single_list=list(itertools.chain.from_iterable(similar_item_userid_list))
    #Unique movieid from the list
    Unique_userid_similar_item=set(similar_item_userid_single_list)
    #Input user watched movie_list
    input_item_watched_userid=list(ratings[ratings['movie_id']==input_item]['user_id'].values)
    #Create a list which should have recom movieid to the input user
    recom=[]
    for per_id in Unique_userid_similar_item:
        if(per_id in input_item_watched_userid):
            pass
        else:
            recom.append(per_id)
    #From recommendation list selecting only hightest rated(predicted) value
    highest_Rated=[]
    user_pred=pd.DataFrame(item_prediction)
    input_item_pre=pd.DataFrame(user_pred[input_item])
    input_item_pred=input_item_pre.T
    for re in recom:
        value=input_item_pred[re].values
        if(value>=thres):
            highest_Rated.append(re)
    highest_Rated
    return highest_Rated

In [56]:
#def userbased(input_user,user_similarity,user_predictions,similar_user_count,similar_user_movieid_count,thres):
Recommended_user=itembased(5,item_similarity,item_pred,5,0.8)

In [57]:
Recommended_user

[59, 279, 416, 450]